name: Hello GitHub Actions

on:
  push:
    branches: [ "main" ]   # Trigger when you push to main

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "🎉 Hello from GitHub Actions!"
